"use client";
import Link from "next/link";
import { catalogueSourceCheckLabel, catalogueUpdateLabel } from "@/lib/site-metadata";
import { useFilterPage } from "@/hooks/use-filter-page";

import { useEffect, useMemo, useState } from "react";
import { Check, CheckCircle2, CircleHelp, Download, Globe2, LibraryBig, Search, ScanSearch, SlidersHorizontal, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Pagination, PaginationContent, PaginationItem } from "@/components/ui/pagination";
import { Empty as CatalogEmpty } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Checkbox } from "@/components/ui/checkbox";
import { getCatalog, getPortfolio, preferredPlan, formatDate, isOlderNav, type Catalog, type CatalogFund, type OfficialPortfolio } from "@/lib/catalog";
import { toCSV } from "@/lib/import";

const count = (v: number) => v.toLocaleString("en-IN");
const nav = (v: number | null | undefined) => v == null ? "Not reported" : `₹${v.toLocaleString("en-IN", { maximumFractionDigits: 4 })}`;
const crore = (v: number) => `₹${(v / 1e7).toLocaleString("en-IN", { maximumFractionDigits: 2 })} cr`;
function Filter({ value, set, label, options }: { value: string; set: (s: string) => void; label: string; options: { value: string; label: string }[] }) {
  return <div className="catalog-filter"><label>{label}</label><Select value={value || "all"} onValueChange={v => set(v === "all" ? "" : v)}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{options.map(o => <SelectItem key={o.value || "all"} value={o.value || "all"}>{o.label}</SelectItem>)}</SelectContent></Select></div>;
}
function Sources({ fund }: { fund: CatalogFund }) {
  const names: Record<string, string> = { portfolio: "Portfolio disclosures", factsheet: "Factsheets", riskometer: "Risk disclosures", annualReport: "Annual reports", information: "Scheme information", website: "Fund house website" };
  return <div className="catalog-source-grid">{Object.entries(names).map(([key, label]) => fund.links[key] ? <a key={key} href={fund.links[key]!} target="_blank" rel="noreferrer">{label}<span>Official fund house</span></a> : <div key={key} className="unavailable-source">{label}<span>Link not supplied by AMFI</span></div>)}</div>;
}
function exportHoldings(portfolio: OfficialPortfolio) {
  const text = toCSV([["fund", "portfolio_date", "security_id", "security_name", "original_source_name", "classification", "source_asset_class", "sector", "calculated_pct_nav", "reported_pct_nav", "market_value_inr", "quantity", "source_sheet", "source_row", "source_url", "source_sha256"], ...portfolio.holdings.map(h => [portfolio.name, portfolio.date, h.id, h.name, h.originalName, h.type, h.assetClass, h.sector, h.weight, h.reportedWeight, h.marketValueINR, h.quantity, portfolio.sourceSheet, h.sourceRow, portfolio.source, portfolio.sourceSha256])]);
  const url = URL.createObjectURL(new Blob([text], { type: "text/csv;charset=utf-8" }));
  const a = document.createElement("a"); a.href = url; a.download = `${portfolio.id}-holdings.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function FundDetail({ fund, latest, selected, toggle }: { fund: CatalogFund; latest: string; selected: boolean; toggle: () => void }) {
  const [planCode, setPlanCode] = useState(preferredPlan(fund)?.code || "");
  const [portfolio, setPortfolio] = useState<OfficialPortfolio | null>(null);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [showAll, setShowAll] = useState(false);
  const [detailTab, setDetailTab] = useState("overview");
  useEffect(() => {
    let active = true;
    if (fund.portfolioId) getPortfolio(fund.id).then(p => { if (active) setPortfolio(p); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [fund.id, fund.portfolioId]);
  const plan = fund.plans.find(p => p.code === planCode) || preferredPlan(fund)!;
  const summary = fund.portfolioSummary;
  const holdings = portfolio?.holdings.filter(h => `${h.name} ${h.id} ${h.sector} ${h.assetClass}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.weight - a.weight) || [];
  return <>
    <SheetHeader className="fund-detail-header"><span className="eyebrow">{fund.amc}</span><SheetTitle>{fund.name}</SheetTitle><SheetDescription>{fund.category} · {fund.structure}</SheetDescription><div className="fund-detail-actions"><span className={`coverage-tag ${summary ? "available" : ""}`}>{summary ? <><CheckCircle2 size={14} /> Holdings available</> : "NAV & official links"}</span>{summary && <Button variant={selected ? "outline" : "default"} onClick={toggle}>{selected ? <><Check size={15} /> Selected for analysis</> : "Add to portfolio lab"}</Button>}</div></SheetHeader>
    <div className="fund-detail-body">
      <Tabs value={detailTab} onValueChange={setDetailTab}><TabsList className="detail-tabs"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="plans">Plans ({fund.plans.length})</TabsTrigger><TabsTrigger value="holdings">Holdings</TabsTrigger></TabsList>
        <TabsContent value="overview">
          <div className="detail-section"><h3>Plan & latest reported NAV</h3><Select value={plan.code} onValueChange={setPlanCode}><SelectTrigger className="w-full" aria-label="Choose fund plan and option"><SelectValue /></SelectTrigger><SelectContent>{fund.plans.map(p => <SelectItem key={p.code} value={p.code}>{p.plan} · {p.option} · {p.code}</SelectItem>)}</SelectContent></Select>
            <div className="detail-nav"><div><span>Net asset value</span><strong>{nav(plan.nav)}</strong></div><div><span>NAV date</span><b>{formatDate(plan.navDate)}</b>{isOlderNav(plan.navDate, latest) && <span className="older-tag">Older record</span>}</div></div>
            <dl className="detail-facts"><div><dt>AMFI scheme code</dt><dd>{plan.code}</dd></div><div><dt>Plan</dt><dd>{plan.plan}</dd></div><div><dt>Option</dt><dd>{plan.option}</dd></div><div><dt>Growth / payout ISIN</dt><dd>{plan.isin || "Not reported"}</dd></div><div><dt>Reinvestment ISIN</dt><dd>{plan.reinvestmentIsin || "Not reported"}</dd></div></dl>
            <p className="small-note">NAV is a per-unit accounting value. It is not a return, rating or indication that a fund is cheaper. Older dates do not establish whether a scheme is currently open to investors.</p>
          </div>
          <div className="detail-section"><h3>Portfolio snapshot</h3>{summary ? <><div className="detail-mini-metrics"><div><span>Reported net assets</span><b>{crore(summary.aumINR)}</b></div><div><span>Holdings date</span><b>{formatDate(summary.date)}</b></div><div><span>Disclosed equity</span><b>{summary.equityPct.toFixed(2)}%</b></div><div><span>Holding rows</span><b>{count(summary.holdingCount)}</b></div></div>{summary.benchmark && <p><strong>Benchmark:</strong> {summary.benchmark}</p>}<p className="small-note">Equity {summary.equityPct.toFixed(2)}% · Cash equivalents {summary.cashPct.toFixed(2)}% · Other assets, net {summary.otherPct.toFixed(2)}%. Other assets can include debt, fund units, metals and net payables. Fund-of-fund units are not looked through to their underlying stocks.</p><Button variant="outline" onClick={() => setDetailTab("holdings")}>Inspect all holdings</Button></> : <div className="catalog-info"><CircleHelp size={18} /><p>A reconciled holdings snapshot is not available in this release. Use the official disclosures below. This fund cannot yet be used in the portfolio lab.</p></div>}</div>
          <div className="detail-section"><h3>Official documents</h3><Sources fund={fund} /><p className="small-note">These links come from AMFI’s fund-house directory. Some lead to a document library where you select this scheme. Expense ratios, exit loads, risk labels, managers and historical returns have not been independently extracted into this catalogue; consult the dated factsheet and scheme documents.</p></div>
        </TabsContent>
        <TabsContent value="plans"><div className="detail-section"><h3>Every reported plan and option</h3><p className="help-text">Records with the same fund-house and scheme name are grouped here. Direct and regular plans may share holdings, but their NAVs differ. Combine their current values for holdings analysis.</p><Table><TableHeader><TableRow><TableHead>Plan / option</TableHead><TableHead className="text-right">NAV</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{[...fund.plans].sort((a, b) => (b.navDate || "").localeCompare(a.navDate || "")).map(p => <TableRow key={p.code}><TableCell><strong>{p.plan}</strong><small className="block">{p.option}</small><small className="block text-muted-foreground">AMFI {p.code} · {p.isin || "ISIN not reported"}</small>{p.reinvestmentIsin && <small className="block text-muted-foreground">Reinvestment: {p.reinvestmentIsin}</small>}</TableCell><TableCell className="text-right">{nav(p.nav)}</TableCell><TableCell>{formatDate(p.navDate)}{isOlderNav(p.navDate, latest) && <span className="older-tag">Older record</span>}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
        <TabsContent value="holdings"><div className="detail-section">{!summary ? <div className="catalog-empty"><LibraryBig size={28} /><h3>Holdings are not available yet</h3><p>The scheme remains searchable in the complete NAV catalogue.</p><Sources fund={fund} /></div> : error ? <p role="alert">{error}</p> : !portfolio ? <p role="status">Loading the official portfolio…</p> : <><div className="catalog-section-heading"><div><h3>Disclosed portfolio</h3><p className="help-text">{formatDate(portfolio.date)} · {count(portfolio.holdings.length)} rows</p></div><Button variant="outline" onClick={() => exportHoldings(portfolio)}><Download size={15} /> CSV</Button></div><div className="catalog-info"><CircleHelp size={18} /><p>Weights below are percentages of reported net assets, calculated from the source market values. The CSV also preserves the original published percentages. Negative net balances are retained. Scenarios model equities only, including when derivatives are disclosed.</p></div><div className="search-box detail-holdings-search"><Search size={16} /><Input aria-label="Search this fund's holdings" placeholder="Search stock, ISIN, sector or asset class" value={search} onChange={e => { setSearch(e.target.value); setShowAll(false); }} /></div><Table><TableHeader><TableRow><TableHead>Security / asset</TableHead><TableHead>Classification</TableHead><TableHead className="text-right">% of NAV</TableHead></TableRow></TableHeader><TableBody>{holdings.slice(0, showAll ? holdings.length : 40).map((h, i) => <TableRow key={`${h.id}-${h.type}-${i}`}><TableCell><strong>{h.name}</strong><small className="block text-muted-foreground">{h.id.startsWith("NONSEC-") ? h.assetClass : h.id}</small><small className="block text-muted-foreground">{h.type === "equity" ? h.sector : h.assetClass}</small></TableCell><TableCell className="capitalize">{h.type === "other" ? "Other assets" : h.type}</TableCell><TableCell className="text-right font-semibold">{h.weight.toFixed(3)}%</TableCell></TableRow>)}</TableBody></Table>{!holdings.length && <p className="catalog-empty">No holdings match this search.</p>}{holdings.length > 40 && !showAll && <Button className="mt-4" variant="outline" onClick={() => setShowAll(true)}>Show all {holdings.length} rows</Button>}<div className="portfolio-provenance"><h4>Source & reconciliation</h4><a className="text-link" href={portfolio.source} target="_blank" rel="noreferrer">Open original AMC disclosure</a><p>{portfolio.note}</p><p>Sheet: {portfolio.sourceSheet} · Net-asset reconciliation difference: {portfolio.reconciliationDifferencePct.toFixed(6)}%.</p><p>Sector and security labels are harmonized by ISIN; original names and row numbers remain in the CSV. No historical holdings or derivative delta exposure are inferred.</p><details><summary>Source file checksum (SHA-256)</summary><code>{portfolio.sourceSha256}</code></details></div></>}</div></TabsContent>
      </Tabs>
    </div>
  </>;
}

export default function FundCatalog() {
  const [catalog, setCatalog] = useState<Catalog | null>(null), [error, setError] = useState("");
  const [query, setQuery] = useState(""), [amc, setAmc] = useState(""), [asset, setAsset] = useState(""), [category, setCategory] = useState(""), [plan, setPlan] = useState(""), [option, setOption] = useState(""), [dateFilter, setDateFilter] = useState(""), [coverage, setCoverage] = useState(""), [sort, setSort] = useState("holdings");
  const [page, setPage] = useFilterPage(JSON.stringify([query, amc, asset, category, plan, option, dateFilter, coverage, sort]));
  const [filtersOpen, setFiltersOpen] = useState(false), [coverageOpen, setCoverageOpen] = useState(false);
  const [detailId, setDetailId] = useState(""), [selected, setSelected] = useState<string[]>([]), [notice, setNotice] = useState("");
  const load = () => { getCatalog().then(c => { setError(""); setCatalog(c); const params = new URLSearchParams(window.location.search); setDetailId(params.get("fund") || ""); setSelected([...new Set((params.get("selected") || "").split(","))].filter(id => c.funds.some(f => f.id === id && f.portfolioId)).slice(0, 20)); }).catch(e => setError(e.message)); };
  useEffect(() => { load(); }, []); // Read URL once; subsequent selection remains in this page.
  const indexed = useMemo(() => catalog?.funds.map(f => ({ fund: f, search: [f.name, f.amc, ...f.plans.flatMap(p => [p.code, p.isin || "", p.reinvestmentIsin || ""])].join(" ").toLowerCase() })) || [], [catalog]);
  const results = useMemo(() => {
    const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
    const list = indexed.filter(({ fund: f, search }) => {
      if (terms.some(t => !search.includes(t)) || amc && f.amc !== amc || asset && f.assetClass !== asset || category && f.category !== category || coverage === "yes" && !f.portfolioId || coverage === "no" && f.portfolioId) return false;
      const p = preferredPlan(f, plan, option); if (!p) return false;
      const older = isOlderNav(p.navDate, catalog?.stats.latestNavDate || "");
      return dateFilter === "recent" ? !older : dateFilter === "older" ? older : true;
    }).map(x => x.fund);
    list.sort((a, b) => sort === "aum" ? (b.portfolioSummary?.aumINR || 0) - (a.portfolioSummary?.aumINR || 0) || a.name.localeCompare(b.name) : sort === "date" ? (preferredPlan(b, plan, option)?.navDate || "").localeCompare(preferredPlan(a, plan, option)?.navDate || "") || a.name.localeCompare(b.name) : sort === "holdings" ? Number(!!b.portfolioId) - Number(!!a.portfolioId) || a.name.localeCompare(b.name) : a.name.localeCompare(b.name));
    return list;
  }, [indexed, catalog, query, amc, asset, category, plan, option, dateFilter, coverage, sort]);
  const detail = catalog?.funds.find(f => f.id === detailId);
  const openDetail = (id: string) => { setDetailId(id); const u = new URL(window.location.href); if (id) u.searchParams.set("fund", id); else u.searchParams.delete("fund"); window.history.replaceState({}, "", u); };
  const toggle = (id: string) => { setNotice(""); if (selected.includes(id)) setSelected(selected.filter(x => x !== id)); else if (selected.length < 20) setSelected([...selected, id]); else setNotice("The portfolio lab supports up to 20 funds at a time."); };
  const houses = useMemo(() => catalog?.houses.map(h => ({ ...h, funds: catalog.funds.filter(f => f.amcId === h.id).length, holdings: catalog.funds.filter(f => f.amcId === h.id && f.portfolioId).length })).sort((a, b) => a.name.localeCompare(b.name)) || [], [catalog]);
  const pages = Math.max(1, Math.ceil(results.length / 40));
  const currentPage = Math.min(page, pages);
  const clear = () => { setQuery(""); setAmc(""); setAsset(""); setCategory(""); setPlan(""); setOption(""); setDateFilter(""); setCoverage(""); };
  return <div className="app-shell catalog-shell">
    <header className="masthead"><Link className="brand" href="/" prefetch={false} aria-label="FundLenz portfolio lab"><span className="brand-mark"><ScanSearch size={25} strokeWidth={1.7} /></span>Fund<span>Lenz</span><span className="brand-divider" /><small>FUND CATALOGUE</small></Link><div className="masthead-right"><Link className="catalog-nav-link" href="/" prefetch={false}>Portfolio lab</Link><Link className="catalog-nav-link" href="/blogpost" prefetch={false}>Blog</Link><span className="project-credit">A project by <strong>Atharva Sahu</strong></span></div></header>
    <main className="workspace catalog-workspace"><nav className="catalog-market-tabs" aria-label="Catalogue market"><a href="/catalogue-global"><Globe2 size={16} /> International</a><a href="/catalogue-india" aria-current="page">India</a><a href="/catalogue-securities">Stocks & bonds</a></nav><p className="small-note">Last catalogue update {catalogueUpdateLabel ?? "not yet recorded"}. Original source-check baseline {catalogueSourceCheckLabel}. Record dates differ. <a className="text-link" href="/data/freshness.json" target="_blank" rel="noreferrer">View freshness checks</a></p><div className="catalog-heading"><div><p className="eyebrow">INDIAN MUTUAL FUNDS · OFFICIAL SOURCE DATA</p><h1>Find the fund. See the holdings.</h1><p>Explore equity, debt, hybrid, index, ETF, fund-of-funds and retirement schemes.</p></div><Button variant="outline" onClick={() => setCoverageOpen(v => !v)}><LibraryBig size={16} /> Data coverage</Button></div>
      {error ? <div className="panel catalog-empty" role="alert"><h2>We couldn’t load the catalogue</h2><p>{error}</p><Button onClick={load}>Try again</Button></div> : !catalog ? <CatalogEmpty className="panel catalog-empty" role="status"><LibraryBig size={30} /><h2>Loading the official fund catalogue…</h2><p>Preparing scheme names, plans, NAV dates and available holdings.</p><Skeleton className="h-4 w-3/4 max-w-xl" /><Skeleton className="h-4 w-1/2 max-w-lg" /></CatalogEmpty> : <>
        <div className="catalog-stats"><div><span>Fund-name records</span><strong>{count(catalog.stats.fundRecords)}</strong><small>{count(catalog.stats.fundHouses)} fund houses</small></div><div><span>Plans & options</span><strong>{count(catalog.stats.planRecords)}</strong><small>Every record in the AMFI feed</small></div><div><span>Portfolios with holdings</span><strong>{count(catalog.stats.holdingsFunds)}</strong><small>{count(catalog.stats.holdingsFundHouses)} fund houses · {formatDate(catalog.stats.holdingsDate)}</small></div><div><span>Latest NAV in this snapshot</span><strong className="stat-date">{formatDate(catalog.stats.latestNavDate)}</strong><small>Dates vary by plan · not a live feed</small></div></div>
        {coverageOpen && <section className="panel coverage-panel"><div className="catalog-section-heading"><div><h2>What this catalogue covers</h2><p className="help-text">Source completeness and holdings coverage are separate.</p></div><Button variant="ghost" size="icon" aria-label="Close data coverage" onClick={() => setCoverageOpen(false)}><X size={18} /></Button></div><p>All {count(catalog.stats.planRecords)} records from the downloaded AMFI NAV feed are included, grouped by fund-house and reported scheme name. These groups can include legacy or renamed schemes; they are not a count of currently active products. Holdings are available only where an official statement was downloaded, matched and reconciled within 0.10 percentage points of reported net assets.</p><div className="coverage-links"><a href={catalog.source} target="_blank" rel="noreferrer">AMFI NAV source</a><a href={catalog.directorySource} target="_blank" rel="noreferrer">AMFI disclosure directory</a><a href="/data/coverage.json" target="_blank" rel="noreferrer">Download coverage & source register</a></div><p className="help-text">Retrieved {formatDate(catalog.retrievedAt)}. Historical returns, expense ratios, exit loads and riskometer labels are not yet extracted. Missing values are not estimated. A fund’s presence here does not establish its availability for new investment.</p><div className="house-coverage-table"><Table><TableHeader><TableRow><TableHead>Fund house</TableHead><TableHead className="text-right">Fund records</TableHead><TableHead className="text-right">Holdings available</TableHead></TableRow></TableHeader><TableBody>{houses.map(h => <TableRow key={h.id}><TableCell><button className="catalog-name" onClick={() => { setAmc(h.name); setCoverageOpen(false); }}>{h.name}</button></TableCell><TableCell className="text-right">{h.funds}</TableCell><TableCell className="text-right">{h.holdings}</TableCell></TableRow>)}</TableBody></Table></div></section>}
        <section className="panel catalog-search-panel"><div className="catalog-search-row"><div className="search-box"><Search size={20} /><Input aria-label="Search all funds" placeholder="Search fund name, fund house, AMFI code or ISIN" value={query} onChange={e => setQuery(e.target.value)} /></div><Button variant="outline" onClick={() => setFiltersOpen(v => !v)} aria-expanded={filtersOpen}><SlidersHorizontal size={16} /> Filters</Button></div><div className="catalog-primary-filters"><Filter label="Fund house" value={amc} set={setAmc} options={[{ value: "", label: "All fund houses" }, ...[...new Set(catalog.funds.map(f => f.amc))].sort().map(a => ({ value: a, label: a }))]} /><Filter label="Asset category" value={asset} set={v => { setAsset(v); setCategory(""); }} options={[{ value: "", label: "All asset categories" }, ...[...new Set(catalog.funds.map(f => f.assetClass))].sort().map(a => ({ value: a, label: a }))]} /><Filter label="Holdings coverage" value={coverage} set={setCoverage} options={[{ value: "", label: "All funds" }, { value: "yes", label: "Holdings available" }, { value: "no", label: "NAV & source links only" }]} /><Filter label="Sort by" value={sort} set={setSort} options={[{ value: "holdings", label: "Holdings available first" }, { value: "name", label: "Fund name A–Z" }, { value: "date", label: "Newest NAV date" }, { value: "aum", label: "Reported net assets" }]} /></div>{filtersOpen && <div className="catalog-secondary-filters"><Filter label="Scheme category" value={category} set={setCategory} options={[{ value: "", label: "All scheme categories" }, ...[...new Set(catalog.funds.filter(f => !asset || f.assetClass === asset).map(f => f.category))].sort().map(a => ({ value: a, label: a }))]} /><Filter label="Plan" value={plan} set={setPlan} options={[{ value: "", label: "All plans" }, { value: "Direct", label: "Direct" }, { value: "Regular", label: "Regular" }]} /><Filter label="Option" value={option} set={setOption} options={[{ value: "", label: "All options" }, { value: "Growth", label: "Growth" }, { value: "IDCW", label: "IDCW" }]} /><Filter label="NAV freshness" value={dateFilter} set={setDateFilter} options={[{ value: "", label: "All dates, including older records" }, { value: "recent", label: "Within 7 days of latest NAV" }, { value: "older", label: "Older / undated records" }]} /></div>}</section>
        <div className="catalog-results-heading"><p><strong>{count(results.length)}</strong> matching fund records</p><div>{[query, amc, asset, category, plan, option, dateFilter, coverage].some(Boolean) && <Button variant="ghost" onClick={clear}>Clear filters</Button>}<span className="small-note">Select portfolios with holdings to analyse them</span></div></div>
        {notice && <div className="notice" role="status"><CircleHelp size={16} />{notice}</div>}
        <section className="panel catalog-results"><Table><TableHeader><TableRow><TableHead className="catalog-check-cell"><span className="sr-only">Select for analysis</span></TableHead><TableHead>Scheme</TableHead><TableHead>Selected plan NAV</TableHead><TableHead>Reported net assets</TableHead><TableHead>Holdings</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{results.slice((currentPage - 1) * 40, currentPage * 40).map(f => {
          const p = preferredPlan(f, plan, option)!; const ps = f.portfolioSummary;
          return <TableRow key={f.id} className={selected.includes(f.id) ? "selected-fund-row" : ""}><TableCell><Checkbox aria-label={`Select ${f.name} for analysis`} checked={selected.includes(f.id)} disabled={!f.portfolioId || selected.length >= 20 && !selected.includes(f.id)} onCheckedChange={() => toggle(f.id)} /></TableCell><TableCell className="catalog-fund-cell"><button className="catalog-name" onClick={() => openDetail(f.id)}>{f.name}</button><small>{f.amc}</small><span className="category-chip">{f.category}</span><small>{f.plans.length} {f.plans.length === 1 ? "plan / option" : "plans / options"}</small></TableCell><TableCell><strong className="nav-amount">{nav(p.nav)}</strong><small className="block">{p.plan} · {p.option}</small><small className="block text-muted-foreground">{formatDate(p.navDate)}</small>{isOlderNav(p.navDate, catalog.stats.latestNavDate) && <span className="older-tag">Older NAV</span>}</TableCell><TableCell>{ps ? <><strong>{crore(ps.aumINR)}</strong><small className="block text-muted-foreground">{formatDate(ps.date)}</small></> : <span className="text-muted-foreground">Not extracted</span>}</TableCell><TableCell>{ps ? <><span className="coverage-tag available"><CheckCircle2 size={14} /> Available</span><small className="block text-muted-foreground">{count(ps.holdingCount)} rows · {ps.equityPct.toFixed(1)}% equity</small></> : <span className="coverage-tag">Not yet available</span>}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={() => openDetail(f.id)} aria-label={`View details for ${f.name}`}>Details</Button></TableCell></TableRow>;
        })}</TableBody></Table>{!results.length && <CatalogEmpty className="catalog-empty"><Search size={30} /><h3>No funds match these filters</h3><p>Try a shorter scheme name or clear the filters.</p><Button variant="outline" onClick={clear}>Clear filters</Button></CatalogEmpty>}<div className="catalog-pagination"><span>{results.length ? `${count((currentPage - 1) * 40 + 1)}–${count(Math.min(currentPage * 40, results.length))} of ${count(results.length)}` : "0 results"}</span><Pagination className="catalog-page-controls"><PaginationContent><PaginationItem><Button variant="outline" disabled={currentPage <= 1} onClick={() => setPage(p => p - 1)}>Previous</Button></PaginationItem><PaginationItem><span className="page-label">Page {currentPage} of {pages}</span></PaginationItem><PaginationItem><Button variant="outline" disabled={currentPage >= pages} onClick={() => setPage(p => p + 1)}>Next</Button></PaginationItem></PaginationContent></Pagination></div></section>
        <p className="catalog-bottom-note">NAV and portfolio dates differ. Fund holdings are a dated snapshot, and source links may have newer disclosures. This catalogue provides factual information and educational calculations; it does not rank funds or recommend investments.</p>
      </>}
    </main>
    {selected.length > 0 && <div className="catalog-selection-bar"><div><strong>{selected.length} {selected.length === 1 ? "fund" : "funds"} selected</strong><span>Enter your current holding values in the portfolio lab.</span></div><div><Button variant="ghost" onClick={() => setSelected([])}>Clear selection</Button><Button asChild><a href={`/?funds=${selected.join(",")}`}>Analyse selected funds</a></Button></div></div>}
    <Sheet open={!!detail} onOpenChange={open => { if (!open) openDetail(""); }}><SheetContent className="fund-detail-sheet" side="right">{detail && <FundDetail key={detail.id} fund={detail} latest={catalog!.stats.latestNavDate} selected={selected.includes(detail.id)} toggle={() => toggle(detail.id)} />}</SheetContent></Sheet>
  </div>;
}
