"use client";
import Link from "next/link";
import { useFilterPage } from "@/hooks/use-filter-page";
import { useDeferredValue, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CircleHelp, Download, Globe2, LibraryBig, ScanSearch, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatDate } from "@/lib/catalog";
import { toCSV } from "@/lib/import";
import { getSecurities, searchSecurities, type Securities, type Security } from "@/lib/securities";
const count = (n: number) => n.toLocaleString("en-US");
function Filter({ label, value, set, values }: { label: string; value: string; set: (v: string) => void; values: string[] }) {
  return <div className="catalog-filter"><label>{label}</label><Select value={value || "__all"} onValueChange={v => set(v === "__all" ? "" : v)}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="__all">All {label.toLowerCase()}</SelectItem>{values.map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>;
}
export default function SecuritiesCatalog() {
  const [catalog,setCatalog] = useState<Securities | null>(null), [error,setError] = useState("");
  const [query,setQuery] = useState(""), [type,setType] = useState(""), [country,setCountry] = useState(""), [currency,setCurrency] = useState("");
  const [sort,setSort] = useState("name"), [detail,setDetail] = useState<Security | null>(null), [coverage,setCoverage] = useState(false);
  const deferred = useDeferredValue(query);
  const [page,setPage] = useFilterPage(JSON.stringify([deferred,type,country,currency,sort]));
  const load = () => { getSecurities().then(data => { setError(""); setCatalog(data); const params = new URLSearchParams(window.location.search); setQuery(params.get("q") || ""); setDetail(data.records.find(r => r.id === params.get("security")) || null); }).catch(e => setError(e.message)); };
  useEffect(load, []);
  useEffect(() => { const pop = () => { const params = new URLSearchParams(window.location.search); setDetail(catalog?.records.find(r => r.id === params.get("security")) || null); }; window.addEventListener("popstate",pop); return () => window.removeEventListener("popstate",pop); }, [catalog]);
  const options = useMemo(() => { const rows = catalog?.records || []; const vals = (key: "type" | "country" | "currency") => [...new Set(rows.map(r => r[key]).filter((x): x is string => !!x))].sort(); return { types: vals("type"), countries: vals("country"), currencies: vals("currency"), bonds: rows.filter(r => r.type === "Bond").length }; },[catalog]);
  const sortedRecords = useMemo(() => [...(catalog?.records || [])].sort((a,b) => sort === "maturity" ? (a.maturity || "9999").localeCompare(b.maturity || "9999") || a.name.localeCompare(b.name) : a.name.localeCompare(b.name)),[catalog,sort]);
  const results = useMemo(() => searchSecurities(sortedRecords,deferred,type,country,currency),[sortedRecords,deferred,type,country,currency]);
  const pages = Math.max(1,Math.ceil(results.length / 40)), current = Math.min(page,pages);
  const clear = () => { setQuery(""); setType(""); setCountry(""); setCurrency(""); setSort("name"); setPage(1); };
  const open = (r: Security | null) => { setDetail(r); const url = new URL(window.location.href); if (r) url.searchParams.set("security",r.id); else url.searchParams.delete("security"); window.history.pushState({},"",url); };
  const exportResults = () => { const csv = toCSV([["id","name","type","symbol","isin","cusip","exchange","source_country","currency","maturity","disclosed_coupon_pct","snapshot","source_urls"],...results.map(r => [r.id,r.name,r.type,r.symbol,r.isin,r.cusip,r.exchange,r.country,r.currency,r.maturity,r.coupon,r.asOf,catalog?.sources.filter(s => r.sourceIds.includes(s.id)).map(s => s.url).join("; ")])]); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a"); a.href=url;a.download="fundlenz-securities.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); };
  return <div className="app-shell">
    <header className="masthead"><Link className="brand" href="/" prefetch={false} aria-label="FundLenz portfolio lab"><span className="brand-mark"><ScanSearch size={25} strokeWidth={1.7}/></span>Fund<span>Lenz</span><span className="brand-divider"/><small>SECURITIES CATALOGUE</small></Link><div className="masthead-right"><Link className="catalog-nav-link" href="/" prefetch={false}>Portfolio lab</Link><span className="project-credit">A project by <strong>Atharva Sahu</strong></span></div></header>
    <main className="workspace catalog-workspace"><nav className="catalog-market-tabs" aria-label="Catalogue market"><a href="/catalogue-global"><Globe2 size={16}/>International</a><a href="/catalogue-india">India</a><a href="/catalogue-securities" aria-current="page">Stocks &amp; bonds</a></nav>
      <div className="catalog-heading"><div><p className="eyebrow">INDIVIDUAL SECURITIES · OFFICIAL SOURCE DATA</p><h1>Explore beyond the fund.</h1><p>Find exchange-listed securities and bonds identified in issuer disclosures.</p></div><Button variant="outline" onClick={()=>setCoverage(!coverage)}><LibraryBig size={16}/>Data coverage</Button></div>
      {error ? <div className="catalog-empty" role="alert"><p>{error}</p><Button onClick={load}>Try again</Button></div> : !catalog ? <p role="status">Loading the securities catalogue…</p> : <>
        <div className="catalog-stats"><div><span>Security reference records</span><strong>{count(catalog.records.length)}</strong><small>Distinct source identifiers</small></div><div><span>Individually identified bonds</span><strong>{count(options.bonds)}</strong><small>Observed in fund holdings, not an exchange list</small></div><div><span>Other listed securities</span><strong>{count(catalog.records.length-options.bonds)}</strong><small>Stock and other listing types shown separately</small></div><div><span>Sources checked</span><strong>{formatDate(catalog.checkedAt)}</strong><small>Each record retains its disclosure date</small></div></div>
        <div className="catalog-info"><CircleHelp size={18}/><p>This is reference data, with no live prices or yield estimates. Bond coverage is a holdings-based sample; coupons are disclosed rates, not yields. Securities here cannot yet be added directly to the fund portfolio lab.</p></div>
        {coverage && <section className="panel coverage-panel"><h2>Coverage and provenance</h2>{catalog.notes?.map((c,i)=><p key={i}>{c}</p>)}<p>Missing fields mean the source did not supply a usable value. Listing type labels follow source names; they are not a prospectus review. A US exchange listing does not establish the issuer’s country.</p>{catalog.sources.map(s=><p key={s.id}><a className="text-link" href={s.url} target="_blank" rel="noreferrer">{s.label || s.id}<ArrowUpRight size={14}/></a> · {formatDate(s.asOf)}</p>)}<a className="text-link" href="/data/securities/audit.json" target="_blank" rel="noreferrer">Download validation and exclusions</a></section>}
        <section className="panel catalog-search-panel"><div className="catalog-search-row"><div className="search-box"><Search size={20}/><Input aria-label="Search stocks and bonds" placeholder="Search name, ticker, ISIN, CUSIP, sector or country" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button variant="outline" onClick={exportResults} disabled={!results.length}><Download size={16}/>Export results</Button></div><div className="catalog-primary-filters"><Filter label="Security types" value={type} set={setType} values={options.types}/><Filter label="Source locations" value={country} set={setCountry} values={options.countries}/><Filter label="Currencies" value={currency} set={setCurrency} values={options.currencies}/><div className="catalog-filter"><label>Sort by</label><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort securities"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="name">Name</SelectItem><SelectItem value="maturity">Maturity, earliest first</SelectItem></SelectContent></Select></div></div><div className="global-quick-search"><span>Quick searches</span>{["AAPL","MSFT","NVIDIA","Treasury","Japan","Germany"].map(q=><button key={q} onClick={()=>{clear();setQuery(q);}}>{q}</button>)}</div></section>
        <div className="catalog-results-heading"><p aria-live="polite"><strong>{count(results.length)}</strong> matching records</p><Button variant="ghost" onClick={clear}>Clear filters</Button></div>
        <section className="panel catalog-results"><Table><TableHeader><TableRow><TableHead>Security</TableHead><TableHead>Identifier</TableHead><TableHead>Type / source location</TableHead><TableHead>Bond terms</TableHead><TableHead>Snapshot</TableHead></TableRow></TableHeader><TableBody>{results.slice((current-1)*40,current*40).map(r=><TableRow key={r.id}><TableCell className="catalog-fund-cell"><button className="catalog-name" onClick={()=>open(r)}>{r.name}</button><small>{r.sector || r.exchange || "Official holdings disclosure"}</small></TableCell><TableCell><strong>{r.symbol || r.isin || r.cusip}</strong>{r.symbol && r.isin && <small className="block">{r.isin}</small>}</TableCell><TableCell>{r.type}<small className="block">{r.country || r.exchange || "Not supplied"}{r.currency ? ` · ${r.currency}` : ""}</small></TableCell><TableCell>{r.type === "Bond" ? <><span>{r.coupon == null ? "Coupon not supplied" : `${r.coupon}% disclosed coupon`}</span><small className="block">{r.maturity ? `Matures ${formatDate(r.maturity)}` : "Maturity not supplied"}</small></> : "—"}</TableCell><TableCell>{formatDate(r.asOf)}</TableCell></TableRow>)}</TableBody></Table>{!results.length && <div className="catalog-empty"><Search size={28}/><h3>No matching securities</h3><p>Try a shorter name or clear the filters.</p></div>}<div className="catalog-pagination"><span>{results.length ? `${count((current-1)*40+1)}–${count(Math.min(current*40,results.length))} of ${count(results.length)}` : "0 results"}</span><div className="catalog-page-controls"><Button variant="outline" disabled={current<=1} onClick={()=>setPage(current-1)}>Previous</Button><span className="page-label">Page {current} of {pages}</span><Button variant="outline" disabled={current>=pages} onClick={()=>setPage(current+1)}>Next</Button></div></div></section>
      </>}
      <footer className="site-footer"><span><ScanSearch size={16}/>FundLenz · Make the holdings visible.</span><a className="footer-contact" href="mailto:info@fundlenz.com">info@fundlenz.com</a><span>Dated source records · No investment recommendations</span></footer>
    </main><Sheet open={!!detail} onOpenChange={v=>{if(!v)open(null);}}><SheetContent className="fund-detail-sheet">{detail && <><SheetHeader className="fund-detail-header"><span className="eyebrow">{detail.type}</span><SheetTitle>{detail.name}</SheetTitle><SheetDescription>Security reference · {formatDate(detail.asOf)}</SheetDescription></SheetHeader><div className="fund-detail-body"><div className="detail-section"><dl className="detail-facts">{[["Symbol",detail.symbol],["ISIN",detail.isin],["CUSIP",detail.cusip],["Exchange",detail.exchange],["Source location",detail.country],["Currency",detail.currency],["Sector",detail.sector],["Maturity",detail.maturity ? formatDate(detail.maturity):undefined],["Disclosed coupon",detail.coupon == null ? undefined : `${detail.coupon}%`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value || "Not supplied"}</dd></div>)}</dl>{detail.note && <p className="small-note">{detail.note}</p>}{detail.maturity && detail.maturity < detail.asOf && <p className="small-note">The disclosed maturity precedes this snapshot. The source still includes this position; current trading or settlement status is not verified.</p>}</div><div className="detail-section"><h3>Source evidence</h3>{catalog?.sources.filter(s=>detail.sourceIds.includes(s.id)).map(s=><div className="portfolio-provenance" key={s.id}><a className="text-link" href={s.url} target="_blank" rel="noreferrer">{s.label || s.id}<ArrowUpRight size={14}/></a><p>Disclosure date: {formatDate(s.asOf)}</p><details><summary>Source checksum (SHA-256)</summary><code>{s.sha256}</code></details></div>)}<p className="small-note">A bond appearing in fund holdings does not establish retail availability, current trading status, a credit rating or a price. Floating-rate coupons can change; maturity alone does not establish callable or perpetual terms.</p></div></div></>}</SheetContent></Sheet>
  </div>;
}
